config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :offers do
      post :disabled
      post :enabled
    end
  end
  root 'home#index'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/offer.rb
class Admin::Offer < ApplicationRecord
  validates :advertiser_name, :description, :start_at, presence: true
  validates :description, length: {  maximum: 500 }
  validates :url, format: URI::regexp(%w[http https])

  enum status: { enabled: 'enabled', disabled: 'disabled' }

  scope :premium_order, -> {
    order('(case when premium then 1 else 0 end) DESC, created_at DESC')
  }
end

app/models/admin/offer_observer.rb
class Admin::OfferObserver < ActiveRecord::Observer

  def before_save(record)
    return if record.status_changed?

    record.status = DateTimeOfferStatus.call(record.start_at, record.ends_at)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/offers_controller.rb
class Admin::OffersController < ApplicationController
  before_action :set_admin_offer,
    only: [:show, :edit, :update, :destroy, :disabled, :enabled]

  def index
    @admin_offers = Admin::Offer.all
  end

  def show
  end

  def new
    @admin_offer = Admin::Offer.new
  end

  def edit
  end

  def create
    @admin_offer = Admin::Offer.new(admin_offer_params)

    if @admin_offer.save
      redirect_to_index_on_success('created.')
    else
      render :new
    end
  end

  def update
    if @admin_offer.update(admin_offer_params)
      redirect_to_index_on_success('updated.')
    else
      render :edit
    end
  end

  def destroy
    @admin_offer.destroy
    redirect_to_index_on_success('destroyed.')
  end

  def disabled
    @admin_offer.disabled!

    respond_to :js
  end

  def enabled
    @admin_offer.enabled!

    respond_to :js
  end

  private

  def redirect_to_index_on_success(message_action)
    flash[:notice] = "Offer was successfully #{message_action}"
    redirect_to admin_offers_path
  end

  def set_admin_offer
    @admin_offer = Admin::Offer.find(params[:id] || params[:offer_id])
  end

  def admin_offer_params
    params.require(:admin_offer).permit(
      :advertiser_name, :url, :description, :start_at, :ends_at, :premium
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < BaseController
  def index
    @offers = Admin::Offer.premium_order.enabled
  end
end

app/helpers/admin/offers_helper.rb
module Admin::OffersHelper
  def status_color(offer)
    offer.enabled? ? 'is-success' : 'is-warning'
  end

  def switch_path_status(offer)
    case offer.status
    when 'enabled'
      admin_offer_disabled_path(offer)
    when 'disabled'
      admin_offer_enabled_path(offer)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def premium_badger(offer)
    if offer.premium?
      content_tag(:span, 'Premium', class: 'tag is-danger is-rounded topcorner')
    end
  end
end

app/views/admin/offers/_form.html.erb
<%= form_with(model: admin_offer, local: true) do |form| %>
  <% if admin_offer.errors.any? %>
     <div class='columns' id='error_explanation'>
      <div class='column'>
        <ul>
        <% admin_offer.errors.full_messages.each do |message| %>
          <li class='help is-danger'><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class='columns is-multiline'>
    <div class='column is-half'>
      <div class='field'>
        <%= form.label :advertiser_name, class: 'label' %>
        <%= form.text_field :advertiser_name, class: 'input' %>
      </div>
    </div>
    <div class='column is-half'>
      <div class='field'>
        <%= form.label :url, class: 'label' %>
        <%= form.text_field :url, class: 'input', placeholder: 'Inicie com http' %>
      </div>
    </div>
    <div class='column is-half'>
      <div classs='field'>
        <%= form.label :description, class: 'label' %>
        <%= form.text_field :description, class: 'textarea' %>
      </div>
    </div>
    <div class='column is-half'>
      <div classs='field'>
        <%= form.label :start_at, class: 'label' %>
        <%= form.text_field :start_at, class: 'input' %>
      </div>
    </div>
    <div class='column is-half'>
      <div classs='field'>
        <%= form.label :ends_at, class: 'label' %>
        <%= form.text_field :ends_at, class: 'input'  %>
      </div>
    </div>
  </div>
  <div class='columns is-multiline'>
    <div class='column is-half'>
      <div classs='field'>
        <%= form.label :premium, class: 'label' %>
        <%= form.check_box :premium, class: 'checkbox' %>
      </div>
    </div>
  </div>

  <div class='actions has-text-right'>
    <%= form.submit 'Save', class: 'button is-primary' %>
    <%= link_to 'Back', admin_offers_path, class: 'button is-dark' %>
  </div>
<% end %>

app/views/admin/offers/_status_url_paths.html.erb
<%= link_to switch_path_status(admin_offer), method: :post, remote: true do %>
  <span class="tag <%= status_color(admin_offer) %>">
    <%= admin_offer.status %>
  </span>
<% end %>

app/views/admin/offers/disabled.js.erb
$('#status_<%= @admin_offer.id %>').html("<%= j (render partial: 'status_url_paths', locals: {admin_offer: @admin_offer}) %>")

app/views/admin/offers/edit.html.erb
<div class="column is-9">
  <h1 class="title">Editing Admin Offer</h1>

  <%= render 'form', admin_offer: @admin_offer %>
</div>

app/views/admin/offers/enabled.js.erb
$('#status_<%= @admin_offer.id %>').html("<%= j (render partial: 'status_url_paths', locals: {admin_offer: @admin_offer}) %>")

app/views/admin/offers/index.html.erb
<div class='column is-9'>

  <h2 class='title'>Offers</h1>

  <div class='card'>
    <header class='card-header'>
      <p class='card-header-title'>
        Offers
      </p>
      <span class='card-header-icon'>
        <%= link_to 'New Offer', new_admin_offer_path, class: 'button is-primary' %>
      </span>
    </header>

    <table class='table is-fullwidth is-hoverable'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Url</th>
          <th>Description</th>
          <th>Start at</th>
          <th>Ends at</th>
          <th>Premium</th>
          <th>Status</th>
          <th colspan='2'>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @admin_offers.each do |admin_offer| %>
          <tr>
            <td><%= admin_offer.advertiser_name %></td>
            <td><%= admin_offer.url %></td>
            <td><%= admin_offer.description.truncate(10) %></td>
            <td><%= admin_offer.start_at %></td>
            <td><%= admin_offer.ends_at %></td>
            <td><%= admin_offer.premium %></td>
            <td id='status_<%= admin_offer.id %>'>
              <%= render 'status_url_paths', admin_offer: admin_offer %>
            </td>
            <td>
              <%= link_to edit_admin_offer_path(admin_offer) do %>
                <span class='fas fa-info-circle has-text-dark'></span>
              <% end %>
            </td>
            <td>
              <%= link_to admin_offer, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class='fas fa-trash-alt has-text-danger'></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/offers/new.html.erb
<div class='column is-9'>
  <h1 class='title'>New Offer</h1>

  <%= render 'form', admin_offer: @admin_offer %>
</div>

app/views/admin/offers/show.html.erb
<div class='column is-9'>
  <div class='card'>
    <div class='card-header'>
      <p class='card-header-title'>
        <span class='fas fa-info mar-rig-1'></span>Offer
      </p>
    </div>
    <div class='card-content'>
      <div class='content'>
        <div class='columns is-multiline'>
          <div class='column is-half'>
            <span class='title is-size-6'>Name</span>
          </div>
          <div class='column is-half'>
            <%= @admin_offer.advertiser_name %>
          </div>

          <div class='column is-half'>
            <span class='title is-size-6'>URL</span>
          </div>
          <div class='column is-half'>
            <%= @admin_offer.url %>
          </div>

          <div class='column is-half'>
            <span class='title is-size-6'>description</span>
          </div>
          <div class='column is-half'>
            <%= @admin_offer.description %>
          </div>

          <div class='column is-half'>
            <span class='title is-size-6'>Start At</span>
          </div>
          <div class='column is-half'>
            <%= @admin_offer.start_at %>
          </div>

          <div class='column is-half'>
            <span class='title is-size-6'>Ends At</span>
          </div>
          <div class='column is-half'>
            <%= @admin_offer.ends_at %>
          </div>

          <div class='column is-half'>
            <span class='title is-size-6'>Premium</span>
          </div>
          <div class='column is-half'>
            <%= @admin_offer.premium %>
          </div>

          <div class='column is-half'>
            <span class='title is-size-6'>Status</span>
          </div>
          <div class='column is-half'>
            <span class='tag <%= status_color(@admin_offer) %>'>
              <%= @admin_offer.status %>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class='card-footer'>
      <div class='card-footer-item'>
        <%= link_to 'Editar', edit_admin_offer_path(@admin_offer),
          class: 'has-text-primary has-text-weight-bold' %>
      </div>
    </div>
  </div>
</div>

app/views/application/_breadcrumb.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="../">Lemmoney Juarez Lustosa Test</a></li>
    <li class="is-active"><a href="#" aria-current="page">Dashboard</a></li>
  </ul>
</nav>

app/views/application/_header.html.erb
<header class="navbar is-dark has-background-grey">
  <div class="container is-fluid">
    <div class="navbar-brand">
      <a class="navbar-item" href="../">
        Juarez Lemmoney test
      </a>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="menu">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <nav class="navbar-menu">
      <div class="navbar-end">
        <div href="#" class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link" aria-haspopup="true" aria-controls="dropdown-menu">
            <span class="pad-rig-1 icon">
              <i class="fas fa-user-circle"></i>
            </span>
            <span>Lemmoney</span>
          </a>
          <div class="navbar-dropdown">
            <%= link_to admin_offers_path, class: "navbar-item" do %>
              <span class="pad-rig-1 icon">
                <i class="fas fa-cog"></i>
              </span>
              Admin Offers
            <% end %>
            <hr class="navbar-divider">
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/application/_hero.html.erb
<section class="hero is-dark is-bold is-rounded">
  <div class="hero-body">
    <div class="container is-fluid">
      <h1 class="title">Dashboard</h1>
      <h2 class="subtitle">
        Hello Welcome to my test
      </h2>
    </div>
  </div>
</section>

app/views/application/_navigation.html.erb
<div class="column is-2">
  <nav class="menu">
    <p class="menu-label">
      Menu
    </p>
    <ul class="menu-list">
      <li>
        <%= link_to root_path do %>
          <span class="icon"><i class="fas fa-tachometer-alt"></i></span>
          Dashboard
        <% end %>
      </li>
      <li>
        <%= link_to admin_offers_path do %>
          <span class="icon"><i class="fas fa-upload"></i></span>Offers
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/application/_notification.html.erb
<div class="column is-12">
  <% if notice %>
    <p class="notification is-success">
      <%= notice %>
    </p>
  <% end %>
  <% if alert %>
    <p class="notification is-danger">
      <%= alert %>
    </p>
  <% end %>
</div>

app/views/home/index.html.erb
<div class='column is-9'>
  <%= render 'hero' %>
  <%= render 'breadcrumb' %>
  <section>
    <div class='tile is-ancestor flex-tile'>
      <% @offers.each do |offer| %>
          <div class='tile is-parent is-6'>
            <div class='tile is-child box notification is-success'>
              <%= premium_badger(offer) %>
              <h4 class='title has-text-centered'><%= offer.advertiser_name %></h4>
              <div class='box-shadow has-text-centered'>
                <%= link_to 'Shop Now', offer.url, class: 'button is-normal' %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Juarezlustosa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <%= render "header" %>
    <%= yield :banner %>
    <main class="section">
      <div class="container is-fluid">
        <div class="columns is-multiline is-centered">
          <%= render "notification" %>
        </div>
        <div class="columns is-multiline is-centered">
          <%= render "navigation" %>
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>